### ISSUE TITLE
Golangci-lint issues with go 1.18.0

### ISSUE THREAD

**Issue by ph** [elastic/fleet-server#1243]
Same as https://github.com/elastic/elastic-agent/issues/224
```` 
Running [/home/runner/golangci-lint-1.44.2-linux-amd64/golangci-lint run --out-format=github-actions --new-from-patch=/tmp/tmp-1596-s1hqw7koKuwO/pull.patch --new=false --new-from-rev= --timeout=5m] in [] ...
  panic: load embedded ruleguard rules: rules/rules.go:13: can't load fmt
  
  goroutine 1 [running]:
  github.com/go-critic/go-critic/checkers.init.22()
  	github.com/go-critic/go-critic@v0.6.2/checkers/embedded_rules.go:46 +0x4b4

**Comment by michel-laterman** [comment]
linter and go version have been updated and this issue no longer occurs
